// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "eY|p-`#c$#hgPunEfXN[":
            case "glassOfH2O":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . 1 1 1 1 1 1 1 . . . . . 
. . . . 1 . . . . . 1 . . . . . 
. . . . 1 . . . . . 1 . . . . . 
. . . . 1 . . . . . 1 . . . . . 
. . . . 1 9 9 9 9 9 1 . . . . . 
. . . . 1 9 9 9 9 9 1 . . . . . 
. . . . 1 9 9 9 9 9 1 . . . . . 
. . . . 1 9 9 9 9 9 1 . . . . . 
. . . . 1 9 9 9 9 9 1 . . . . . 
. . . . 1 9 9 9 9 9 1 . . . . . 
. . . . 1 9 9 9 9 9 1 . . . . . 
. . . . 1 9 9 9 9 9 1 . . . . . 
. . . . 1 1 1 1 1 1 1 . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "compy":
            case "xC}M]@;*zw":return [img`
.....bbbbbbbbb......
....b1ddddddd1b.....
...b11111111111b....
...bdbcccccccbdb....
...bdc6666666cdb....
...bdc6d66666cdb....
...bdc6666666cdb....
...bdc6666666cdb....
...bdc6666666cdb....
...bdcccccccccdb....
...cbbbbbbbbbbbc....
..cbcccccccccccbc...
..c1ddddddddddd1c...
..cccc1d11d11d11ccc.
..cbbbbbbbbbbbbbc...
..ccccccccccccccc...
.....cc......cc.....
.....cc......cc.....
.....cc......cc.....
.....cc......cc.....
`, img`
.....bbbbbbbbb......
....b1ddddddd1b.....
...b11111111111b....
...bdbcccccccbdb....
...bdc6666666cdb....
...bdc6d66666cdb....
...bdc6666666cdb....
...bdc6666666cdb....
...bdc6666666cdb....
...bdcccccccccdb....
...cbbbbbbbbbbbc....
..cbcccccccccccbc...
..c1ddddddddddd1c...
ccc11d1d11d11cccc...
..cbbbbbbbbbbbbbc...
..ccccccccccccccc...
.....cc......cc.....
.....cc......cc.....
.....cc......cc.....
.....cc......cc.....
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
